---
config:
  theme: neo
  layout: fixed
  look: neo
---
flowchart TD
 subgraph VSGSeq_individual["__VSGSeq_individual__"]
        Result["Result"]
        A_10_6_1_result["A_10_6_1_result"]
        A1["A_10_6_1"]
        A_10_6_2_result["A_10_6_2_result"]
        B1["A_10_6_2"]
        A_10_6_3_result["A_10_6_3_result"]
        C1["A_10_6_3"]
        A_10_7_1_result["A_10_7_1_result"]
        D1["A_10_7_1"]
        A_10_7_2_result["A_10_7_2_result"]
        E1["A_10_7_2"]
        A_10_7_3_result["A_10_7_3_result"]
        F1["A_10_7_3"]
        B_10_6_1_result["B_10_6_1_result"]
        G1["B_10_6_1"]
        B_10_6_2_result["B_10_6_2_result"]
        H1["B_10_6_2"]
        B_10_6_3_result["B_10_6_3_result"]
        I1["B_10_6_3"]
        B_10_7_1_result["B_10_7_1_result"]
        J1["B_10_7_1"]
        B_10_7_2_result["B_10_7_2_result"]
        K1["B_10_7_2"]
        B_10_7_3_result["B_10_7_3_result"]
        L1["B_10_7_3"]
  end
 subgraph vsgseq2["__vsgseq2__"]
        M3["Combine"]
        A3["A_10_6_1"]
        B3["A_10_6_2"]
        C3["A_10_6_3"]
        D3["A_10_7_1"]
        E3["A_10_7_2"]
        F3["A_10_7_3"]
        G3["B_10_6_1"]
        H3["B_10_6_2"]
        I3["B_10_6_3"]
        J3["B_10_7_1"]
        K3["B_10_7_2"]
        L3["B_10_7_3"]
        N3["Result"]
  end
 subgraph VSGSeq_combined["__VSGSeq_combined__"]
        M2["Combine"]
        A2["A_10_6_1"]
        B2["A_10_6_2"]
        C2["A_10_6_3"]
        D2["A_10_7_1"]
        E2["A_10_7_2"]
        F2["A_10_7_3"]
        G2["B_10_6_1"]
        H2["B_10_6_2"]
        I2["B_10_6_3"]
        J2["B_10_7_1"]
        K2["B_10_7_2"]
        L2["B_10_7_3"]
        N2["Result"]
  end
    A1 --> A_10_6_1_result
    A_10_6_1_result --> Result
    B1 --> A_10_6_2_result
    A_10_6_2_result --> Result
    C1 --> A_10_6_3_result
    A_10_6_3_result --> Result
    D1 --> A_10_7_1_result
    A_10_7_1_result --> Result
    E1 --> A_10_7_2_result
    A_10_7_2_result --> Result
    F1 --> A_10_7_3_result
    A_10_7_3_result --> Result
    G1 --> B_10_6_1_result
    B_10_6_1_result --> Result
    H1 --> B_10_6_2_result
    B_10_6_2_result --> Result
    I1 --> B_10_6_3_result
    B_10_6_3_result --> Result
    J1 --> B_10_7_1_result
    B_10_7_1_result --> Result
    K1 --> B_10_7_2_result
    B_10_7_2_result --> Result
    L1 --> B_10_7_3_result
    B_10_7_3_result --> Result
    A2 --> M2
    B2 --> M2
    C2 --> M2
    D2 --> M2
    E2 --> M2
    F2 --> M2
    G2 --> M2
    H2 --> M2
    I2 --> M2
    J2 --> M2
    K2 --> M2
    L2 --> M2
    M2 --> N2
    A3 --> M3
    B3 --> M3
    C3 --> M3
    D3 --> M3
    E3 --> M3
    F3 --> M3
    G3 --> M3
    H3 --> M3
    I3 --> M3
    J3 --> M3
    K3 --> M3
    L3 --> M3
    M3 --> N3

